# coding: utf-8

"""
    ❤️ Русский корабль, иди нахуй! ❤️

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ddos_cluster_api import DDOSClusterApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDDOSClusterApi(unittest.TestCase):
    """DDOSClusterApi unit test stubs"""

    def setUp(self):
        self.api = DDOSClusterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_d_dos_get_active_tasks(self):
        """Test case for d_dos_get_active_tasks

        """
        pass

    def test_d_dos_get_active_workers(self):
        """Test case for d_dos_get_active_workers

        """
        pass

    def test_d_dos_get_damage_stats(self):
        """Test case for d_dos_get_damage_stats

        """
        pass

    def test_d_dos_upsert_worker(self):
        """Test case for d_dos_upsert_worker

        """
        pass


if __name__ == '__main__':
    unittest.main()
