# coding: utf-8

"""
    ❤️ Русский корабль, иди нахуй! ❤️

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ddos_task_dto import DDOSTaskDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestDDOSTaskDTO(unittest.TestCase):
    """DDOSTaskDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDDOSTaskDTO(self):
        """Test DDOSTaskDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ddos_task_dto.DDOSTaskDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
