# coding: utf-8

"""
    ❤️ Русский корабль, иди нахуй! ❤️

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.swagger_api import SwaggerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSwaggerApi(unittest.TestCase):
    """SwaggerApi unit test stubs"""

    def setUp(self):
        self.api = SwaggerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_swagger_get_json(self):
        """Test case for swagger_get_json

        """
        pass

    def test_swagger_get_ui(self):
        """Test case for swagger_get_ui

        """
        pass


if __name__ == '__main__':
    unittest.main()
