# coding: utf-8

# flake8: noqa
"""
    ❤️ Русский корабль, иди нахуй! ❤️

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.ddos_task_dto import DDOSTaskDTO
from swagger_client.models.ddos_worker import DDOSWorker
from swagger_client.models.ddos_worker_dto import DDOSWorkerDTO
