# coding: utf-8

"""
    ❤️ Русский корабль, иди нахуй! ❤️

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DDOSTaskDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ip_address_or_domain': 'str',
        'requests_count': 'int'
    }

    attribute_map = {
        'ip_address_or_domain': 'ipAddressOrDomain',
        'requests_count': 'requestsCount'
    }

    def __init__(self, ip_address_or_domain=None, requests_count=None):  # noqa: E501
        """DDOSTaskDTO - a model defined in Swagger"""  # noqa: E501
        self._ip_address_or_domain = None
        self._requests_count = None
        self.discriminator = None
        self.ip_address_or_domain = ip_address_or_domain
        self.requests_count = requests_count

    @property
    def ip_address_or_domain(self):
        """Gets the ip_address_or_domain of this DDOSTaskDTO.  # noqa: E501


        :return: The ip_address_or_domain of this DDOSTaskDTO.  # noqa: E501
        :rtype: str
        """
        return self._ip_address_or_domain

    @ip_address_or_domain.setter
    def ip_address_or_domain(self, ip_address_or_domain):
        """Sets the ip_address_or_domain of this DDOSTaskDTO.


        :param ip_address_or_domain: The ip_address_or_domain of this DDOSTaskDTO.  # noqa: E501
        :type: str
        """
        if ip_address_or_domain is None:
            raise ValueError("Invalid value for `ip_address_or_domain`, must not be `None`")  # noqa: E501

        self._ip_address_or_domain = ip_address_or_domain

    @property
    def requests_count(self):
        """Gets the requests_count of this DDOSTaskDTO.  # noqa: E501


        :return: The requests_count of this DDOSTaskDTO.  # noqa: E501
        :rtype: int
        """
        return self._requests_count

    @requests_count.setter
    def requests_count(self, requests_count):
        """Sets the requests_count of this DDOSTaskDTO.


        :param requests_count: The requests_count of this DDOSTaskDTO.  # noqa: E501
        :type: int
        """
        if requests_count is None:
            raise ValueError("Invalid value for `requests_count`, must not be `None`")  # noqa: E501

        self._requests_count = requests_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DDOSTaskDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DDOSTaskDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
